In [1]:
# Task 6: K-Nearest Neighbors (KNN) Classification
# Elevate Labs AI & ML Internship
# Dataset: Iris Dataset

# ─────────────────────────────────────────────
# STEP 1: Import Libraries
# ─────────────────────────────────────────────
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (
    accuracy_score, confusion_matrix, classification_report
)

import warnings
warnings.filterwarnings("ignore")

In [2]:
# ─────────────────────────────────────────────
# STEP 2: Load and Explore Dataset
# ─────────────────────────────────────────────
df = pd.read_csv("Iris.csv")
print("=== Dataset Shape ===")
print(df.shape)

print("\n=== First 5 Rows ===")
print(df.head())

print("\n=== Dataset Info ===")
print(df.info())

print("\n=== Class Distribution ===")
print(df["Species"].value_counts())

# Drop 'Id' column — not a feature
df.drop(columns=["Id"], inplace=True)

=== Dataset Shape ===
(150, 6)

=== First 5 Rows ===
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

=== Dataset Info ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes:

In [3]:
# ─────────────────────────────────────────────
# STEP 3: Define Features and Target
# ─────────────────────────────────────────────
X = df.drop(columns=["Species"])
y = df["Species"]

# Encode target labels
le = LabelEncoder()
y_encoded = le.fit_transform(y)   # 0, 1, 2
class_names = le.classes_          # ['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']


In [4]:
# ─────────────────────────────────────────────
# STEP 4: Normalize Features (StandardScaler)
# KNN is distance-based → normalization is CRITICAL
# ─────────────────────────────────────────────
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [5]:
# ─────────────────────────────────────────────
# STEP 5: Train-Test Split
# ─────────────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

print(f"\nTraining samples : {X_train.shape[0]}")
print(f"Testing  samples : {X_test.shape[0]}")


Training samples : 120
Testing  samples : 30


In [6]:
# ─────────────────────────────────────────────
# STEP 6: Experiment with Different K Values
# ─────────────────────────────────────────────
k_range = range(1, 21)
train_accuracies = []
test_accuracies  = []

for k in k_range:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    train_accuracies.append(accuracy_score(y_train, knn.predict(X_train)))
    test_accuracies.append(accuracy_score(y_test,  knn.predict(X_test)))

print("\n=== Accuracy vs K ===")
for k, acc in zip(k_range, test_accuracies):
    print(f"  K={k:2d}  →  Test Accuracy: {acc:.4f}")

# Best K
best_k = k_range[np.argmax(test_accuracies)]
print(f"\n✅ Best K = {best_k}  (Test Accuracy = {max(test_accuracies):.4f})")



=== Accuracy vs K ===
  K= 1  →  Test Accuracy: 0.9667
  K= 2  →  Test Accuracy: 0.9333
  K= 3  →  Test Accuracy: 0.9333
  K= 4  →  Test Accuracy: 0.9333
  K= 5  →  Test Accuracy: 0.9333
  K= 6  →  Test Accuracy: 0.9333
  K= 7  →  Test Accuracy: 0.9667
  K= 8  →  Test Accuracy: 0.9333
  K= 9  →  Test Accuracy: 0.9667
  K=10  →  Test Accuracy: 0.9667
  K=11  →  Test Accuracy: 0.9667
  K=12  →  Test Accuracy: 0.9667
  K=13  →  Test Accuracy: 0.9667
  K=14  →  Test Accuracy: 0.9333
  K=15  →  Test Accuracy: 0.9333
  K=16  →  Test Accuracy: 0.9333
  K=17  →  Test Accuracy: 0.9667
  K=18  →  Test Accuracy: 0.9667
  K=19  →  Test Accuracy: 0.9667
  K=20  →  Test Accuracy: 0.9333

✅ Best K = 1  (Test Accuracy = 0.9667)


In [7]:
# ─────────────────────────────────────────────
# STEP 7: Train Final Model with Best K
# ─────────────────────────────────────────────
knn_best = KNeighborsClassifier(n_neighbors=best_k)
knn_best.fit(X_train, y_train)
y_pred = knn_best.predict(X_test)

print("\n=== Classification Report ===")
print(classification_report(y_test, y_pred, target_names=class_names))



=== Classification Report ===
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.91      1.00      0.95        10
 Iris-virginica       1.00      0.90      0.95        10

       accuracy                           0.97        30
      macro avg       0.97      0.97      0.97        30
   weighted avg       0.97      0.97      0.97        30



In [8]:
# ─────────────────────────────────────────────
# STEP 8: Confusion Matrix
# ─────────────────────────────────────────────
cm = confusion_matrix(y_test, y_pred)
print("=== Confusion Matrix ===")
print(cm)

=== Confusion Matrix ===
[[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]


In [9]:
# ─────────────────────────────────────────────
# STEP 9: Visualizations (5 plots saved as PNG)
# ─────────────────────────────────────────────
colors = ["#E76F51", "#2A9D8F", "#264653"]
plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 11})

# --- Plot 1: Accuracy vs K ---
fig, ax = plt.subplots(figsize=(9, 5))
ax.plot(k_range, train_accuracies, "o--", color="#E76F51", label="Train Accuracy", linewidth=2)
ax.plot(k_range, test_accuracies,  "o-",  color="#2A9D8F", label="Test Accuracy",  linewidth=2)
ax.axvline(best_k, color="#264653", linestyle=":", linewidth=1.8, label=f"Best K={best_k}")
ax.set_xlabel("K (Number of Neighbors)")
ax.set_ylabel("Accuracy")
ax.set_title("KNN: Accuracy vs K Value", fontsize=14, fontweight="bold")
ax.legend()
ax.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("plot1_accuracy_vs_k.png", dpi=150)
plt.close()
print("Saved: plot1_accuracy_vs_k.png")


Saved: plot1_accuracy_vs_k.png


In [10]:
# --- Plot 2: Confusion Matrix Heatmap ---
fig, ax = plt.subplots(figsize=(7, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="YlGnBu",
            xticklabels=class_names, yticklabels=class_names, ax=ax,
            linewidths=0.5, linecolor="gray")
ax.set_xlabel("Predicted Label")
ax.set_ylabel("True Label")
ax.set_title(f"Confusion Matrix (K={best_k})", fontsize=14, fontweight="bold")
plt.xticks(rotation=30, ha="right")
plt.tight_layout()
plt.savefig("plot2_confusion_matrix.png", dpi=150)
plt.close()
print("Saved: plot2_confusion_matrix.png")

Saved: plot2_confusion_matrix.png


In [11]:
# --- Plot 3: Pairplot of raw features ---
fig, axes = plt.subplots(1, 2, figsize=(11, 4))
feature_pairs = [("SepalLengthCm", "SepalWidthCm"), ("PetalLengthCm", "PetalWidthCm")]
for ax, (fx, fy) in zip(axes, feature_pairs):
    for i, (cls, col) in enumerate(zip(class_names, colors)):
        mask = df["Species"] == cls
        ax.scatter(df.loc[mask, fx], df.loc[mask, fy],
                   color=col, label=cls, alpha=0.7, edgecolors="white", linewidth=0.4)
    ax.set_xlabel(fx); ax.set_ylabel(fy)
    ax.set_title(f"{fx} vs {fy}", fontweight="bold")
    ax.legend(fontsize=8); ax.grid(alpha=0.3)
plt.suptitle("Feature Scatter Plots — Iris Dataset", fontsize=13, fontweight="bold", y=1.02)
plt.tight_layout()
plt.savefig("plot3_scatter_features.png", dpi=150)
plt.close()
print("Saved: plot3_scatter_features.png")

Saved: plot3_scatter_features.png


In [12]:
# --- Plot 4: Decision Boundary (2 features: PetalLength vs PetalWidth) ---
feat_idx = [2, 3]   # PetalLengthCm, PetalWidthCm (best separability)
X2 = X_scaled[:, feat_idx]
X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)
knn2 = KNeighborsClassifier(n_neighbors=best_k)
knn2.fit(X2_train, y2_train)

x_min, x_max = X2[:, 0].min() - 0.5, X2[:, 0].max() + 0.5
y_min, y_max = X2[:, 1].min() - 0.5, X2[:, 1].max() + 0.5
xx, yy = np.meshgrid(np.linspace(x_min, x_max, 300),
                      np.linspace(y_min, y_max, 300))
Z = knn2.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)

fig, ax = plt.subplots(figsize=(8, 6))
cmap_bg = plt.cm.RdYlGn
ax.contourf(xx, yy, Z, alpha=0.25, cmap=cmap_bg)
for i, (cls, col) in enumerate(zip(class_names, colors)):
    mask = y_encoded == i
    ax.scatter(X2[mask, 0], X2[mask, 1], color=col, label=cls,
               edgecolors="white", linewidth=0.5, s=60, alpha=0.9)
ax.set_xlabel("PetalLengthCm (scaled)")
ax.set_ylabel("PetalWidthCm (scaled)")
ax.set_title(f"KNN Decision Boundary (K={best_k})", fontsize=14, fontweight="bold")
ax.legend(); ax.grid(alpha=0.25)
plt.tight_layout()
plt.savefig("plot4_decision_boundary.png", dpi=150)
plt.close()
print("Saved: plot4_decision_boundary.png")

# --- Plot 5: Feature Importance via Variance ---
feat_names = X.columns.tolist()
variances = X.var().values
fig, ax = plt.subplots(figsize=(7, 4))
bars = ax.barh(feat_names, variances, color=["#E76F51","#2A9D8F","#264653","#E9C46A"])
ax.set_xlabel("Variance")
ax.set_title("Feature Variance (proxy for spread/importance)", fontsize=13, fontweight="bold")
for bar, v in zip(bars, variances):
    ax.text(bar.get_width() + 0.01, bar.get_y() + bar.get_height()/2,
            f"{v:.3f}", va="center", fontsize=10)
ax.grid(axis="x", alpha=0.3); ax.invert_yaxis()
plt.tight_layout()
plt.savefig("plot5_feature_variance.png", dpi=150)
plt.close()
print("Saved: plot5_feature_variance.png")

print("\n✅ All plots saved. Script complete!")


Saved: plot4_decision_boundary.png
Saved: plot5_feature_variance.png

✅ All plots saved. Script complete!
